
version: "3.9"
services:
  db:
    image: postgres:13.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - gameData:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"

volumes:
  gameData: